### ISSUE TITLE
Where is medoid used?

### ISSUE THREAD

**Issue by r-matsuzaka** [juglab/EmbedSeg#14]
Hi.

I have a question about implementation about medoid which is mentioned in the paper.
I found the calculation of it is done at https://github.com/juglab/EmbedSeg/blob/50f23233cf9564ff443c67c45a611ce665571c12/EmbedSeg/utils/generate_crops.py#L84

But I could not found the clue that this funtion is called from any other python scripts.

Could you tell me how the medoid is used in the code?

**Comment by r-matsuzaka** [comment]
Sorry, I found https://github.com/juglab/EmbedSeg/blob/main/examples/2d/dsb-2018/01-data.ipynb
It is called as process_one_hot.

**Comment by MLbyML** [comment]
Hello @r-matsuzaka Thanks for looking into the code. The medoid, as you found out, is used by the **[process](https://github.com/juglab/EmbedSeg/blob/50f23233cf9564ff443c67c45a611ce665571c12/EmbedSeg/utils/generate_crops.py#L169)** function which makes a call to the **[generate_center_image](https://github.com/juglab/EmbedSeg/blob/50f23233cf9564ff443c67c45a611ce665571c12/EmbedSeg/utils/generate_crops.py#L84)** function --> this is where the medoid is computed.

**Comment by r-matsuzaka** [comment]
Thank you so much!
