### ISSUE TITLE
[BUG]RuntimeError: result type Byte can't be cast to the desired output type Bool

### ISSUE THREAD

**Issue by r-matsuzaka** [juglab/EmbedSeg#17]
Hi, again..

When I run `begin_evaluating(test_configs, verbose = False, avg_bg= avg_bg/normalization_factor)` at [predict notebook](https://github.com/juglab/EmbedSeg/blob/main/examples/2d/bbbc010-2012/03-predict.ipynb),
I got the following error:

```
2-D `test` dataloader created! Accessing data from ../../../data/bbbc010-2012/test/
Number of images in `test` directory is 50
Number of instances in `test` directory is 50
Number of center images in `test` directory is 0
*************************
Creating branched erfnet with [4, 1] classes
```

>   0%|          | 0/50 [00:01<?, ?it/s]
>- - - - - - -
>
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_33/4185926816.py in <module>
> ----> 1 begin_evaluating(test_configs, verbose = False, avg_bg= avg_bg/normalization_factor)
> 
> /kaggle/input/embedsegv1/EmbedSeg/test.py in begin_evaluating(test_configs, verbose, mask_region, mask_intensity, avg_bg)
>      62         test(verbose = verbose, grid_x = test_configs['grid_x'], grid_y = test_configs['grid_y'],
>      63              pixel_x = test_configs['pixel_x'], pixel_y = test_configs['pixel_y'],
> ---> 64              one_hot = test_configs['dataset']['kwargs']['one_hot'], avg_bg = avg_bg, n_sigma=n_sigma)
>      65     elif(test_configs['name']=='3d'):
>      66         test_3d(verbose=verbose,
> 
> /kaggle/input/embedsegv1/EmbedSeg/test.py in test(verbose, grid_y, grid_x, pixel_y, pixel_x, one_hot, avg_bg, n_sigma)
>     126 
>     127             center_x, center_y, samples_x, samples_y, sample_spatial_embedding_x, sample_spatial_embedding_y, sigma_x, sigma_y, \
> --> 128             color_sample_dic, color_embedding_dic = prepare_embedding_for_test_image(instance_map = instance_map, output = output, grid_x = grid_x, grid_y = grid_y, pixel_x = pixel_x, pixel_y =pixel_y, predictions =predictions, n_sigma = n_sigma)
>     129 
>     130             base, _ = os.path.splitext(os.path.basename(sample['im_name'][0]))
> 
> /kaggle/input/embedsegv1/EmbedSeg/utils/utils.py in prepare_embedding_for_test_image(instance_map, output, grid_x, grid_y, pixel_x, pixel_y, predictions, n_sigma)
>     483         sample_spatial_embedding_y[id.item()] = add_samples(samples_spatial_embeddings, 1, grid_y - 1, pixel_y)
>     484         center_image = predictions[id.item() - 1]['center-image']  # predictions is a list!
> --> 485         center_mask = in_mask & center_image.byte()
>     486 
>     487 
> 
> RuntimeError: result type Byte can't be cast to the desired output type Bool

**Comment by r-matsuzaka** [comment]
BTW I am now trying to use your method for ongoing kaggle cell segmentation competition.
Is it okay for you?

**Comment by MLbyML** [comment]
Hello @r-matsuzaka Using this in a kaggle challenge is fine for me :)
Regarding the error message, my initial guess is the bug could be linked to the pytorch version (We use currently `pytorch=1.10.0` and `cudatoolkit=10.2`). Could you please check if you have similar versions of these packages, say by running `conda list`? Thanks.

**Comment by r-matsuzaka** [comment]
> Hello @r-matsuzaka Using this in a kaggle challenge is fine for me :)
Thank you so much. I am very happy to hear that.


> Regarding the error message, my initial guess is the bug could be linked to the pytorch version (We use currently pytorch=1.10.0 and cudatoolkit=10.2). Could you please check if you have similar versions of these packages, say by running conda list?

Thank you for your suggestion.
When I tried conda list, I found that cudatoolkit=11.0.221 and torch=1.9.1.

And when I serch `RuntimeError: result type Byte can't be cast to the desired output type Bool` by google, I found a lot of similar issue due to version. So I am trying to fix by myself.
If I found the solution or any progress, I will share it here.

Thank you.

**Comment by r-matsuzaka** [comment]
I close this issue once because this is not a bug of this repository.

**Comment by r-matsuzaka** [comment]
Excuse me, what data type should `center_mask ` have?

**Comment by r-matsuzaka** [comment]
@MLbyML 
[line 485 at utils.py](https://github.com/juglab/EmbedSeg/blob/50f23233cf9564ff443c67c45a611ce665571c12/EmbedSeg/utils/utils.py#L485)

I changed:

before
center_mask = in_mask & center_image.byte()

after
center_mask = in_mask.to(torch.int16) & center_image

Then, it worked.

**Comment by r-matsuzaka** [comment]
When I run only one epoch, then I got black image for inference.
Is it normal?
