### ISSUE TITLE
Trouble installing dependencies

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [juglab/EmbedSeg#26]
Hello team, thank for this repo! While installing EmbedSeg and creating the env, I get the error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.2
```

Any ideas how to bypass this?

Thanks, Ajinkya

**Comment by nunopimpaomartins** [comment]
Hello Ajinkya,

What OS are you using?

Probably cudatoolkit is no longer available in pytorch channel.
you could try other channels like `conda install cudatoolkit=10.2 -c conda-forge`

Can you try this?

Nuno

**Comment by ajinkya-kulkarni** [comment]
I installed cudatoolkit without a specific version - it worked for now. Let's see.
